version: "3.7"

services:
  termsite:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    expose:
      - '3005'
    ports:
      - '3005:3000'
    volumes:
      - ./src/:/home/node/app/src
      - /home/node/app/node_modules
    command: npm run dev

  termsite-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    expose:
      - '3006'
    ports:
      - '3006:3000'
    command: npm start
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
