version: "3.7"
services:
  bigsk1:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3005'
    ports:
      - '3005:3000'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev
