version: "3.7"
services:
  bigsk1:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3005'
    ports:
      - '3005:3000'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev

  bigsk1-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    expose:
      - '3006'
    ports:
      - '3006:3000'
    command: npm start
